# Generated by Django 2.2.2 on 2019-06-12 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=30)),
                ('zanr', models.CharField(max_length=10)),
                ('glumci', models.CharField(max_length=150)),
                ('vreme_trajanja', models.DurationField()),
            ],
        ),
        migrations.CreateModel(
            name='Projekcija',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('film', models.CharField(max_length=150)),
                ('vreme_pocetka', models.DateTimeField()),
                ('sala', models.IntegerField()),
                ('cena_karte', models.IntegerField()),
                ('status', models.CharField(choices=[('IM', 'Ima Mesta'), ('POP', 'Popunjeno')], default='IM', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broj_sale', models.IntegerField()),
                ('broj_redova', models.IntegerField()),
                ('broj_sedista_red', models.IntegerField()),
            ],
        ),
    ]
